### ISSUE TITLE
Remove Python 2

### ISSUE THREAD

**Issue by offa** [jhnc-oss/meta-protos#145]
Remove Python 2 recipes and layer.

- [x] SIP — #147

**Comment by offa** [comment]
_Nothing left here_

**Comment by offa** [comment]
Sip depends on Python2 :see_no_evil:

**Comment by offa** [comment]
@h5b should we backport this to dunfell so we can close #65?

**Comment by h5b** [comment]
> @h5b should we backport this to dunfell so we can close #65?

Not sure as we might break legacy releases based on dunfell.
