### ISSUE TITLE
Scarthgap support

### ISSUE THREAD

**Issue by offa** [jhnc-oss/meta-protos#235]
This layer needs scarthgap support (ie. branch).

**Comment by h5b** [comment]
I beg to differ, meta-protos has been merges into protos with the advent of poky/scarthgap as it no longer seems reasonable to split these to (we also consume it in this form in downstream already) and it is considered are more yoctish(tm) way as well.

**Comment by offa** [comment]
Oh, didn't notice … :sweat_smile: 

Should we then to the same for kirkstone (and dunfell?) too and retire this repo?

**Comment by h5b** [comment]
> Oh, didn't notice … 😅
> 
> Should we then do the same for kirkstone (and dunfell?) too and retire this repo?
I suggest to keep kirkstone and dunfell as is, as this still reflects the way of doing it back then but scarthgap is a different kind of an animal and in addition, the splitting didn't prove to be reasonable any longer. Therfore, switching now while keeping the legacy seems to be fine imvho.

**Comment by offa** [comment]
I have opened a PR with a deprecation notice (#236).
We can close here.
