### ISSUE TITLE
Planning: Switching to upcoming future LTS release

### ISSUE THREAD

**Issue by h5b** [jhnc-oss/meta-protos#44]
According to the Yocto Project https://wiki.yoctoproject.org/wiki/Releases the next Long Term Support release will be **Kirkstone** (poky 27.0.x) available in April 2022.

This surely implies coping with the following technical debt:

- getting rid of [meta-qt5 ](https://github.com/jhnc-oss/meta-qt5/tree/backport/5.12.4-dunfell-23.0.11) backport and switching to qt5 version as supported by Kirkstone

**Comment by offa** [comment]
@h5b can we close here? All steps are planed through the project.

**Comment by h5b** [comment]
Yes, go ahead.
